// @generated automatically by Diesel CLI.

diesel::table! {
    /// Representation of the `bookings` table.
    ///
    /// (Automatically generated by Diesel.)
    bookings (id) {
        /// The `id` column of the `bookings` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `bookings` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `calendar_connection_id` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        calendar_connection_id -> Nullable<Uuid>,
        /// The `idempotency_key` column of the `bookings` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        #[max_length = 128]
        idempotency_key -> Varchar,
        /// The `status` column of the `bookings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Text,
        /// The `starts_at` column of the `bookings` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        starts_at -> Timestamptz,
        /// The `ends_at` column of the `bookings` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        ends_at -> Timestamptz,
        /// The `attendee_name` column of the `bookings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        attendee_name -> Text,
        /// The `attendee_email` column of the `bookings` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        attendee_email -> Text,
        /// The `attendee_time_zone` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        attendee_time_zone -> Nullable<Text>,
        /// The `message` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        message -> Nullable<Text>,
        /// The `provider_event_id` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        provider_event_id -> Nullable<Text>,
        /// The `provider_event_etag` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        provider_event_etag -> Nullable<Text>,
        /// The `last_error_code` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        last_error_code -> Nullable<Text>,
        /// The `confirmed_at` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        confirmed_at -> Nullable<Timestamptz>,
        /// The `cancelled_at` column of the `bookings` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        cancelled_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `bookings` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `bookings` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `calendar_connections` table.
    ///
    /// (Automatically generated by Diesel.)
    calendar_connections (id) {
        /// The `id` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_id` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `provider` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        provider -> Text,
        /// The `provider_account_id` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        provider_account_id -> Text,
        /// The `calendar_id` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        calendar_id -> Text,
        /// The `credentials_ciphertext` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Bytea`.
        ///
        /// (Automatically generated by Diesel.)
        credentials_ciphertext -> Bytea,
        /// The `credentials_key_id` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        credentials_key_id -> Text,
        /// The `scopes` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Array<Nullable<Text>>`.
        ///
        /// (Automatically generated by Diesel.)
        scopes -> Array<Nullable<Text>>,
        /// The `token_expires_at` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        token_expires_at -> Nullable<Timestamptz>,
        /// The `status` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        status -> Text,
        /// The `last_error_code` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        last_error_code -> Nullable<Text>,
        /// The `last_synced_at` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        last_synced_at -> Nullable<Timestamptz>,
        /// The `created_at` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `calendar_connections` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `did` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        did -> Text,
        /// The `handle` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        handle -> Nullable<Text>,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
    }
}

diesel::joinable!(bookings -> calendar_connections (calendar_connection_id));
diesel::joinable!(bookings -> users (user_id));
diesel::joinable!(calendar_connections -> users (user_id));

diesel::allow_tables_to_appear_in_same_query!(bookings, calendar_connections, users,);
